import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import useAuth from '../hooks/useAuth';
import { MdQuiz, MdDashboard, MdTrendingUp, MdSpeed, MdCheckCircle } from 'react-icons/md';
import { FaBrain, FaClock, FaChartLine, FaBook, FaRocket } from 'react-icons/fa';

function Home() {
  const { isAuthenticated, user } = useAuth();

  const features = [
    {
      icon: FaBrain,
      title: 'AI-Powered Questions',
      description: 'Get personalized quiz questions generated by advanced AI based on your difficulty level.',
      color: 'text-purple-500',
      bgColor: 'bg-purple-50'
    },
    {
      icon: FaClock,
      title: 'Smart Timer',
      description: 'Adaptive time limits based on question difficulty and your performance history.',
      color: 'text-orange-500',
      bgColor: 'bg-orange-50'
    },
    {
      icon: MdTrendingUp,
      title: 'Progress Tracking',
      description: 'Monitor your improvement with detailed analytics and performance insights.',
      color: 'text-green-500',
      bgColor: 'bg-green-50'
    }
  ];

  const benefits = [
    'Unlimited quiz attempts',
    'Instant AI feedback',
    'Performance analytics',
    'Mobile-friendly design'
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-orange-50">
      
      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            
            {/* Left Content */}
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="mb-6">
                <span className="inline-block px-4 py-2 bg-orange-100 text-orange-600 rounded-full text-sm font-semibold mb-4">
                  🎓 B.TECH LEARNING PLATFORM
                </span>
              </div>
              
              <h1 className="text-5xl md:text-6xl font-bold text-gray-800 mb-6 leading-tight">
                Master Your<br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-orange-600">
                  B.Tech Subjects
                </span><br />
                with AI
              </h1>
              
              <p className="text-xl text-gray-600 mb-8 leading-relaxed">
                Practice DBMS, OS, Computer Networks, and DSA with intelligent AI-powered quizzes. 
                Get instant feedback and track your progress in real-time.
              </p>

              {/* CTA Buttons */}
              {isAuthenticated ? (
                <div className="flex flex-wrap gap-4">
                  <Link 
                    to="/dashboard"
                    className="px-8 py-4 bg-gradient-to-r from-orange-400 to-orange-500 text-white rounded-2xl font-bold hover:from-orange-500 hover:to-orange-600 shadow-lg hover:shadow-xl transform hover:-translate-y-1 transition-all duration-200 inline-flex items-center space-x-2"
                  >
                    <MdDashboard className="text-xl" />
                    <span>Go to Dashboard</span>
                  </Link>
                  <Link 
                    to="/quiz-selection"
                    className="px-8 py-4 bg-white text-gray-800 rounded-2xl font-bold border-2 border-gray-200 hover:border-orange-500 hover:text-orange-500 shadow-md hover:shadow-lg transform hover:-translate-y-1 transition-all duration-200 inline-flex items-center space-x-2"
                  >
                    <MdQuiz className="text-xl" />
                    <span>Start Quiz</span>
                  </Link>
                </div>
              ) : (
                <div className="flex flex-wrap gap-4">
                  <Link 
                    to="/register"
                    className="px-8 py-4 bg-gradient-to-r from-orange-400 to-orange-500 text-white rounded-2xl font-bold hover:from-orange-500 hover:to-orange-600 shadow-lg hover:shadow-xl transform hover:-translate-y-1 transition-all duration-200 inline-flex items-center space-x-2"
                  >
                    <FaRocket />
                    <span>Get Started Free</span>
                  </Link>
                  <Link 
                    to="/login"
                    className="px-8 py-4 bg-white text-gray-800 rounded-2xl font-bold border-2 border-gray-200 hover:border-orange-500 hover:text-orange-500 shadow-md hover:shadow-lg transform hover:-translate-y-1 transition-all duration-200"
                  >
                    Login
                  </Link>
                </div>
              )}

              {/* Stats - Removed */}
              {/* Stats section removed as requested */}
            </motion.div>

            {/* Right Illustration */}
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative"
            >
              <div className="relative">
                {/* Main Animated Circle */}
                <motion.div
                  animate={{ 
                    rotate: 360,
                  }}
                  transition={{ 
                    duration: 20, 
                    repeat: Infinity, 
                    ease: "linear" 
                  }}
                  className="relative w-full aspect-square max-w-md mx-auto"
                >
                  {/* Outer Ring */}
                  <div className="absolute inset-0 border-8 border-orange-200 rounded-full"></div>
                  
                  {/* Orbiting Icons */}
                  <motion.div
                    animate={{ rotate: -360 }}
                    transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2"
                  >
                    <div className="bg-blue-500 rounded-full p-4 shadow-xl">
                      <FaBook className="text-3xl text-white" />
                    </div>
                  </motion.div>

                  <motion.div
                    animate={{ rotate: -360 }}
                    transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    className="absolute top-1/2 right-0 translate-x-1/2 -translate-y-1/2"
                  >
                    <div className="bg-green-500 rounded-full p-4 shadow-xl">
                      <MdSpeed className="text-3xl text-white" />
                    </div>
                  </motion.div>

                  <motion.div
                    animate={{ rotate: -360 }}
                    transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    className="absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2"
                  >
                    <div className="bg-purple-500 rounded-full p-4 shadow-xl">
                      <FaChartLine className="text-3xl text-white" />
                    </div>
                  </motion.div>

                  <motion.div
                    animate={{ rotate: -360 }}
                    transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                    className="absolute top-1/2 left-0 -translate-x-1/2 -translate-y-1/2"
                  >
                    <div className="bg-orange-500 rounded-full p-4 shadow-xl">
                      <MdQuiz className="text-3xl text-white" />
                    </div>
                  </motion.div>
                </motion.div>

                {/* Center Brain Icon */}
                <motion.div
                  animate={{ 
                    scale: [1, 1.1, 1],
                  }}
                  transition={{ 
                    duration: 3, 
                    repeat: Infinity,
                    ease: "easeInOut"
                  }}
                  className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full p-12 shadow-2xl"
                >
                  <FaBrain className="text-6xl text-white" />
                </motion.div>

                {/* Floating Particles */}
                {[...Array(6)].map((_, i) => (
                  <motion.div
                    key={i}
                    animate={{
                      y: [0, -30, 0],
                      opacity: [0.3, 1, 0.3],
                    }}
                    transition={{
                      duration: 3 + i,
                      repeat: Infinity,
                      delay: i * 0.5,
                      ease: "easeInOut"
                    }}
                    className="absolute bg-orange-300 rounded-full"
                    style={{
                      width: `${Math.random() * 10 + 5}px`,
                      height: `${Math.random() * 10 + 5}px`,
                      top: `${Math.random() * 100}%`,
                      left: `${Math.random() * 100}%`,
                    }}
                  />
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto max-w-6xl px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-800 mb-4">
              Why Choose QuizMaster?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Everything you need to excel in your B.Tech exams
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-gradient-to-br from-gray-50 to-white p-8 rounded-3xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
              >
                <div className={`${feature.bgColor} w-16 h-16 rounded-2xl flex items-center justify-center mb-6`}>
                  <feature.icon className={`text-3xl ${feature.color}`} />
                </div>
                <h3 className="text-xl font-bold text-gray-800 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Subjects Section - Removed */}
      {/* Subjects section removed as requested */}

      {/* Benefits Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto max-w-6xl px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            
            {/* Left - Benefits List */}
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl font-bold text-gray-800 mb-6">
                Everything You Need to Succeed
              </h2>
              <p className="text-xl text-gray-600 mb-8">
                Join thousands of students improving their grades with QuizMaster
              </p>
              
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.4, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    className="flex items-center space-x-4 bg-orange-50 p-4 rounded-2xl"
                  >
                    <div className="bg-orange-500 rounded-full p-2">
                      <MdCheckCircle className="text-2xl text-white" />
                    </div>
                    <span className="text-lg font-medium text-gray-800">
                      {benefit}
                    </span>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            {/* Right - Image Placeholder */}
            <motion.div
              initial={{ opacity: 0, x: 50 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="bg-gradient-to-br from-orange-100 to-orange-200 rounded-3xl p-12 text-center">
                <FaBook className="text-[150px] text-orange-400 mx-auto" />
                <div className="mt-8">
                  <div className="text-4xl font-bold text-gray-800 mb-2">50,000+</div>
                  <div className="text-lg text-gray-600">Questions Available</div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      {!isAuthenticated && (
        <section className="py-20 bg-gradient-to-r from-orange-400 to-orange-500">
          <div className="container mx-auto max-w-4xl px-4 text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Ready to Boost Your Grades?
              </h2>
              <p className="text-xl text-orange-100 mb-8">
                Join thousands of students already improving with QuizMaster
              </p>
              <Link
                to="/register"
                className="inline-block px-10 py-5 bg-white text-orange-500 rounded-2xl font-bold text-lg hover:bg-gray-100 shadow-2xl hover:shadow-3xl transform hover:-translate-y-1 transition-all duration-200"
              >
                Start Learning Today →
              </Link>
            </motion.div>
          </div>
        </section>
      )}
    </div>
  );
}

export default Home;